### ISSUE TITLE
Typo in article

### ISSUE THREAD

**Issue by laurentvd** [imteekay/thinking-in-types#1]
Hi, great article! I wanted to create a PR for the article itself, but there's a typo in secutiryCode (security vs secutiry) in the PaymentMethod example. Cheers

**Comment by imteekay** [comment]
Hi @laurentvd, thanks for the issue! Feel free to open a PR to this repo and for the [article repo](https://github.com/leandrotk/tk/blob/master/2020/07/a-mental-model-to-think-in-typescript/index.html). Let me know if you need anything!

**Comment by laurentvd** [comment]
Ah thanks @leandrotk, I didn't realize there was a repo for the articles as well. I've made the PR at https://github.com/leandrotk/tk/pull/83

**Comment by imteekay** [comment]
Great, @laurentvd! Thanks for your contribution! 
Feel free to open a PR for this repo too if you have any interest/time.
